# Generated by Django 3.1.1 on 2021-03-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog_post')),
                ('title', models.CharField(max_length=60)),
                ('dec', models.TextField(max_length=1000)),
                ('pdate', models.DateField()),
                ('cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField()),
                ('file1', models.FileField(default='', upload_to='image', verbose_name='Image_view')),
            ],
        ),
        migrations.CreateModel(
            name='Genquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=90)),
                ('op2', models.CharField(max_length=90)),
                ('op3', models.CharField(max_length=90)),
                ('op4', models.CharField(max_length=90)),
                ('correct', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Scc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=90)),
                ('op2', models.CharField(max_length=90)),
                ('op3', models.CharField(max_length=90)),
                ('op4', models.CharField(max_length=90)),
                ('correct', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Highschool',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pdf.common')),
                ('sub', models.CharField(max_length=34)),
            ],
            bases=('pdf.common',),
        ),
        migrations.CreateModel(
            name='India',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pdf.common')),
                ('exam1', models.CharField(max_length=34)),
            ],
            bases=('pdf.common',),
        ),
        migrations.CreateModel(
            name='Statelevel',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pdf.common')),
                ('exam', models.CharField(max_length=45)),
            ],
            bases=('pdf.common',),
        ),
    ]
