# Generated by Django 3.1.1 on 2021-03-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pdate',
            new_name='pdate1',
        ),
    ]
