# Generated by Django 3.1.1 on 2021-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20210313_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pdate1',
        ),
    ]
